### ISSUE TITLE
Will it run on x86 or x64 system?

### ISSUE THREAD

**Issue by coderboyisongithub** [tangziwen/Cube-Engine#7]
I have x64 based have windows system ,here with  visual studio 2012...so whats your answer about that?

**Comment by tangziwen** [comment]
Hi, Currently X64 Only, because the voxel terrain‘s memory usage is huge compare to height map terrain.
I don't think VS 2012 can compile the engine without modified, because I use some C++14/17 feature in codes.

**Comment by tangziwen** [comment]
no plan to implement x86 version
